name: Python Hello World

on:
  push:
    branches: [ main ]

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    env:
      GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GOOGLE_CREDENTIALS }}'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install wheel
        python -m pip install twine
        python -m pip install keyrings.google-artifactregistry-auth
    - name: Build Package
      run: |
        python setup.py sdist bdist_wheel
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Upload to Artifact Registry
      run: |
        gcloud config set artifacts/repository foo
        gcloud config set artifacts/location us-central1
        gcloud config set account github-gcr-service-account@norrin-radd.iam.gserviceaccount.com
        gcloud auth activate-service-account github-gcr-service-account@norrin-radd.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=norrin-radd
        gcloud artifacts print-settings python > ~/.pypirc
        python -m twine upload --repository foo dist/*
      